Repository VictoriaMetrics/VictoriaMetrics, pull requests merged in 2025-08, with the labels that each got.

#9443 .github/workflows: Run cross builds and tests in parallel
  .github/workflows/build.yml
  .github/workflows/test.yml
  Makefile
  lib/appmetrics/appmetrics.go
Labels: chore

#9572 apptest: fix flaky single vmauth router with auth test
  apptest/vmauth.go
Labels: chore

#9575 apptest: Fix flaky TestSingleVMAuthRouterWithAuth
  apptest/vmagent.go
  apptest/vmauth.go
Labels: chore

#9463 app/vmui: add export functionality for Query and RawQuery tabs with CSV/JSON support
  app/vmui/packages/vmui/src/api/query-range.ts
  app/vmui/packages/vmui/src/components/DownloadButton/DownloadButton.tsx
  app/vmui/packages/vmui/src/components/Main/Icons/index.tsx
  app/vmui/packages/vmui/src/pages/CustomPanel/DownloadReport/DownloadReport.tsx
  app/vmui/packages/vmui/src/pages/CustomPanel/index.tsx
  app/vmui/packages/vmui/src/pages/CustomPanel/utils.test.ts
  app/vmui/packages/vmui/src/pages/CustomPanel/utils.ts
  app/vmui/packages/vmui/src/pages/RawQueryPage/hooks/useFetchExport.ts
  app/vmui/packages/vmui/src/pages/RawQueryPage/index.tsx
  app/vmui/packages/vmui/src/utils/csv.test.ts
  app/vmui/packages/vmui/src/utils/csv.ts
  app/vmui/packages/vmui/src/utils/file.ts
  docs/victoriametrics/changelog/CHANGELOG.md
Labels: vmui

#9617 lib/prompb: replace fields hardcoded hex values with their correspond…
  lib/prompb/marshal.go
Labels: chore

#9621 app/vmagent/remotewrite: restore protocol downgrade logic
  app/vmagent/remotewrite/client.go
Labels: bug, vmagent

#9489 app/vmstorage: labels api delegate to inverted index if only `__name__` in `match`
  lib/storage/index_db.go
  lib/storage/index_db_test.go
Labels: enhancement, performance, vmstorage
